# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test Go

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: Build on Linux
      run: GOOS=linux GOARCH=amd64 go build -o myapp-linux
    - name: Run tests
      run: go test ./...

  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: '^1.18'
  #   - name: Build on Windows
  #     run: GOOS=windows GOARCH=amd64 go build -o myapp-windows.exe
  #   - name: Run tests
  #     run: go test ./...

